services:
  mongodb:
    image: mongo:latest
    container_name: mymongo
    network_mode: "host"

  spark-master:
    image: docker.io/bitnami/spark:2
    container_name: my_spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    network_mode: "host"

  spark-worker:
    image: docker.io/bitnami/spark:2
    container_name: my_spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://pc:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    network_mode: "host"
    depends_on:
      - spark-master
